export const projects = [
  {
    name: "ChatsApp",
    coverImage: "/images/chatsapp.png",
    liveSite: "https://chatsapp-web.vercel.app",
    github: "https://github.com/exploitenomah/chatsapp_fe",
    description:
      "A whatsapp web clone built with socket.io for instant messaging in the browser.",
    tags: [
      "typescript",
      "react.js",
      "next.js",
      "socket.io",
      "reduxjs/toolkit",
      "react-redux",
      "react-dom",
      "tailwindCss",
    ],
  },
  {
    name: "GCMM",
    coverImage: "/images/gcmm.png",
    liveSite: "https://goldencitymodelsng.netlify.app/",
    github: "https://github.com/Golden-City-Model-Management/GCMM",
    description: "Volunteer website project for Golden City Model Management.",
    tags: [
      "typescript",
      "react.js",
      "next.js",
      "cypress",
      "reduxjs/toolkit",
      "react-redux",
      "react-dom",
      "materialUI",
    ],
  },
  {
    name: "MDEditor",
    coverImage: "/images/mdeditor.png",
    liveSite: "https://markdown-editor-iota.vercel.app/",
    github: "https://github.com/exploitenomah/MarkdownEditor",
    description:
      "A web based markdown editor that lets you write markdown in the browser.",
    tags: [
      "typescript",
      "react.js",
      "next.js",
      "reduxjs/toolkit",
      "react-redux",
      "react-dom",
      "tailwindCss",
    ],
  },
  {
    name: "Hair Definition",
    coverImage: "/images/hairdef.png",
    liveSite: "https://hairdefinition.netlify.app/",
    github: "https://github.com/exploitenomah/hairdefinition",
    description: "Website for a fictional hair styling company.",
    tags: ["react.js", "react-dom", "styled-components"],
  },
  {
    name: "Shortly",
    coverImage: "/images/shortly.png",
    liveSite: "https://shortly-fem.vercel.app/",
    github: "https://github.com/exploitenomah/ShortlyFEM",
    description: "URL Shortner for easy shortening of links!",
    tags: [
      "typescript",
      "react.js",
      "next.js",
      "react-dom",
      "react-icons",
      "tailwindCss",
    ],
  },
]
